### ISSUE TITLE
[BUG]: Regex for email validation is not working correctly

### ISSUE THREAD

**Issue by YossefAbdelMohsen** [ahmed0saber/quran_mailer#4]
The regex for email validation is not working correctly. It is not allowing valid email addresses to pass through the validation. If the email starts with capital letter or number.

**Comment by ahmed0saber** [comment]
Hello @YossefAbdelMohsen , can you let me know how to reproduce this bug? what should I do in which page to see that an invalid email is getting accepted?

**Comment by YossefAbdelMohsen** [comment]
Hi,
Here as you can see the email is valid but it start with capital letter so it gives me an error
![image](https://github.com/ahmed0saber/quran_mailer/assets/129265865/b68b2466-2b53-4845-a18b-56473e43f84f)

also here the first letter is a number but it gives me an error as well
![image](https://github.com/ahmed0saber/quran_mailer/assets/129265865/a2e68c81-4e24-45c5-a743-30b8c16b98ff)

**Comment by ahmed0saber** [comment]
Ok, understood.
